<?php
/*
 * Dokuwiki's Main Configuration File - Local Settings
 * Auto-generated by config plugin
 * Run for user: vmadmin
 * Date: Sat, 03 Apr 2021 00:02:15 +0200
 */

$conf['title'] = 'Allround Informatik AG';
$conf['lang'] = 'de';
$conf['template'] = 'typowiki';
$conf['sidebar'] = 'Allround Informatik AG';
$conf['license'] = 'cc-by-sa';
$conf['showuseras'] = 'username';
$conf['useacl'] = 1;
$conf['superuser'] = '@admin';
$conf['disableactions'] = 'register';
$conf['target']['extern'] = 'blank';
$conf['userewrite'] = '1';
$conf['useslash'] = 1;
$conf['proxy']['user'] = 'vmadmin';
$conf['proxy']['pass'] = '<b>c21sMTIzNDU=';
$conf['tpl']['argon']['hideTools'] = '1';
$conf['tpl']['argon']['showIcon'] = '1';
$conf['tpl']['material']['dokuwikiSidebar'] = '1';
$conf['tpl']['material']['feedbackForm'] = '0';
$conf['tpl']['material']['technicalFeedbackForm'] = '0';
$conf['tpl']['material']['feedbackEmail'] = 'natiqkhan00@gmail.com';
$conf['tpl']['material']['hiddenActions'] = 'edit,backlink,top';
$conf['tpl']['material']['subtlePagename'] = '1';
