<?php
/*
 * Dokuwiki's Main Configuration File - Local Settings
 * Auto-generated by config plugin
 * Run for user: vmadmin
 * Date: Thu, 01 Apr 2021 19:37:25 +0200
 */

$conf['title'] = 'Allround Informatik AG';
$conf['template'] = 'material';
$conf['license'] = 'cc-by-sa';
$conf['useacl'] = 1;
$conf['superuser'] = '@admin';
$conf['disableactions'] = 'register';
$conf['proxy']['user'] = 'vmadmin';
$conf['proxy']['pass'] = '<b>c21sMTIzNDU=';
$conf['tpl']['material']['dokuwikiSidebar'] = 1;
$conf['tpl']['material']['feedbackEmail'] = 'natiqkhan00@gmail.com';
