<?php
/*
 * Dokuwiki's Main Configuration File - Local Settings
 * Auto-generated by config plugin
 * Run for user: vmadmin
 * Date: Thu, 01 Apr 2021 20:28:33 +0200
 */

$conf['title'] = 'Allround Informatik AG';
$conf['template'] = 'argon';
$conf['sidebar'] = 'Allround Informatik AG';
$conf['license'] = 'cc-by-sa';
$conf['useacl'] = 1;
$conf['superuser'] = '@admin';
$conf['disableactions'] = 'register';
$conf['proxy']['user'] = 'vmadmin';
$conf['proxy']['pass'] = '<b>c21sMTIzNDU=';
$conf['tpl']['material']['dokuwikiSidebar'] = '1';
$conf['tpl']['material']['feedbackForm'] = '0';
$conf['tpl']['material']['technicalFeedbackForm'] = '0';
$conf['tpl']['material']['feedbackEmail'] = 'natiqkhan00@gmail.com';
$conf['tpl']['material']['hiddenActions'] = 'edit,backlink,top';
$conf['tpl']['material']['subtlePagename'] = '1';
