# users.auth.php
# <?php exit()?>
# Don't modify the lines above
#
# Userfile
#
# Auto-generated by install script
# Date: Fri, 19 Feb 2021 09:26:47 +0000
#
# Format:
# login:passwordhash:Real Name:email:groups,comma,separated

vmadmin:$2y$10$ShHri4xIxFbNWY71B2qxceKST98/MecW1oTfDQO.EvAFvq7l3Qoee:vmadmin:vmadmin@gibb.ch:admin,user
